### What is a programming language?
Rules that convert strings and numbers to some "machine code output". We use programming languages in our cohort because it allows us to speed up the rate which we perform tasks, such as by making it easier to:
1. Analyze and visualize data 
2. Run machine learning algorithms
You could do all of this by hand, but I wouldn't recommend it. It'd be quite painful. 

### What is Python? Why do we use Python?
Python is an example of a programming language. It's known for being easy to learn and being one of the best languages to conduct data analysis in. We use Python for those reasons above. Python is easy to conduct data analysis in because it has many powerful libraries which make it convenient to work with data, and run machine learning algorithms. Instead of having to code the algorithms yourself, you can reference these libraries. 
Some examples: sklearn (machine learning library), pandas and numpy (data analysis and visualization library)

### What is a script? What is a notebook?
A script is a file (think like a .docx) that contains code you write. Scripts are specific to each programming language, and python scripts have .py extensions. All the code in a script is "run" in one go. 
A notebook is a file that also contains code you write, but the code is split up into chunks called cells. You run code by cell, and it's a lot faster/more convenient if you want to just visualize preliminary results. Deepnote is a platform that allows you to run python notebooks on it - we use it because it's really convenient and doesn't require installation. 
To use deepnote, create an account and click create a notebook. 

### What is code?
Most of what you write in a notebook/python is code (except this - this is markdown). I will now write code to demonstrate what python can do. 
### What is a function?
In python, you can call functions that will do things. That's very vague so here's an example:

In [7]:
import numpy as np
print(np.sqrt(4))
print(np.log(3))

2.0
1.0986122886681096


### What is a variable? 
We store information in python in variables. Here's an example. Please name your variables something relevant to what they are.
lst contains a list, which is a type of data structure in python. lists contain multiple things. 

In [13]:
number = 3
lst = np.random.random(6) # generates 50 random numbers between 0 and 1 (see uniform distribution)
print(number)
print(lst)

3
[0.61264521 0.94334628 0.38731571 0.07596609 0.2095585  0.76249275]


You can perform functions on variables, and you can assign the output to the same or another variable or you can leave it unsaved. What's great about python is this property called vectorization - you can call np.log on a list or multiply it by 3 and it will give you the natural log of every element in a list. You cannot do this in every programming language. 

In [15]:
print(np.sqrt(number))
log_lst = np.log(lst)
print(log_lst)
times_3_lst = lst * 3
print(times_3_lst)

1.7320508075688772
[-0.48996929 -0.05832185 -0.94851513 -2.57746827 -1.56275234 -0.27116228]
[1.83793563 2.83003885 1.16194712 0.22789826 0.6286755  2.28747825]


A for loop allows you to iterate through the contents of a list. See the two examples of how to do so with a for loop that produce the same output. We can either reference the objects in a list, or we can reference the position an object is in a list. 

In [16]:
animals = ['dog', 'cat', 'bird']
for animal in animals:
    print("The plural of " + animal + " is " + animal + "s")

The plural of dog is dogs
The plural of cat is cats
The plural of bird is birds


In [17]:
animals = ['dog', 'cat', 'bird']
for i in range(len(animals)):
    print("The plural of " + animals[i] + " is " + animals[i] + "s")

The plural of dog is dogs
The plural of cat is cats
The plural of bird is birds


### Conclusion
This is what you will need to know for us to go through the machine learning notebooks. For a more detailed introduction, see the following 3 links (should be read sequentially in order).
1. https://python-programming.quantecon.org/python_by_example.html
2. https://python-programming.quantecon.org/functions.html
3. https://python-programming.quantecon.org/python_essentials.html

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=2f36f187-e4c0-43eb-9741-7f08ff3a54db' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>